import { MigrationInterface, QueryRunner } from 'typeorm'

export class AddManyToOneId1669705524137 implements MigrationInterface {
  name = 'AddManyToOneId1669705524137'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE "user" ADD "poliBagianId" integer')
    await queryRunner.query('ALTER TABLE "kunjungan" ADD "reservasiId" integer NOT NULL')
    await queryRunner.query('ALTER TABLE "bhp" DROP CONSTRAINT "FK_65192ba6227c61db00ddd026eb6"')
    await queryRunner.query('ALTER TABLE "bhp" ALTER COLUMN "refBhpId" SET NOT NULL')
    await queryRunner.query('ALTER TABLE "reservasi" DROP CONSTRAINT "FK_fcda02184a2a199580e4c5a0774"')
    await queryRunner.query('ALTER TABLE "reservasi" DROP CONSTRAINT "FK_14fa2860224a19d7cd9740d3a61"')
    await queryRunner.query('ALTER TABLE "reservasi" ALTER COLUMN "poliBagianId" SET NOT NULL')
    await queryRunner.query('ALTER TABLE "reservasi" ALTER COLUMN "dokterId" SET NOT NULL')
    await queryRunner.query('ALTER TABLE "kunjungan" DROP CONSTRAINT "FK_815a30c04caaea6cac8e0bfd703"')
    await queryRunner.query('ALTER TABLE "kunjungan" DROP CONSTRAINT "FK_97aacbe549c64c25bb53ba09014"')
    await queryRunner.query('ALTER TABLE "kunjungan" ALTER COLUMN "userId" SET NOT NULL')
    await queryRunner.query('ALTER TABLE "kunjungan" ALTER COLUMN "penyakitId" SET NOT NULL')
    await queryRunner.query('ALTER TABLE "obat" DROP CONSTRAINT "FK_674d2a594b62b922dba2a8b6fac"')
    await queryRunner.query('ALTER TABLE "obat" DROP CONSTRAINT "FK_2a6ec97144614ccc0bdcbb25b0d"')
    await queryRunner.query('ALTER TABLE "obat" ALTER COLUMN "kunjunganPoliId" SET NOT NULL')
    await queryRunner.query('ALTER TABLE "obat" ALTER COLUMN "refObatId" SET NOT NULL')
    await queryRunner.query('ALTER TABLE "tindakan" DROP CONSTRAINT "FK_a542af81b59d3e65d593a77b999"')
    await queryRunner.query('ALTER TABLE "tindakan" DROP CONSTRAINT "FK_c47fb5ed4f33fcf2d0597c415b6"')
    await queryRunner.query('ALTER TABLE "tindakan" ALTER COLUMN "refTindakanId" SET NOT NULL')
    await queryRunner.query('ALTER TABLE "tindakan" ALTER COLUMN "kunjunganPoliId" SET NOT NULL')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" DROP CONSTRAINT "FK_0cefc763fa7bb353c3a9b8c533c"')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" DROP CONSTRAINT "FK_291f6490928c9a9a28876bb13bd"')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" DROP CONSTRAINT "FK_cc75ba6e19b43a6756e076808b7"')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" DROP CONSTRAINT "FK_3cd38b1b696f348d3117538254b"')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ALTER COLUMN "poliBagianId" SET NOT NULL')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ALTER COLUMN "dokterId" SET NOT NULL')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ALTER COLUMN "perawatId" SET NOT NULL')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ALTER COLUMN "penyakitId" SET NOT NULL')
    await queryRunner.query('ALTER TABLE "bhp" ADD CONSTRAINT "FK_65192ba6227c61db00ddd026eb6" FOREIGN KEY ("refBhpId") REFERENCES "ref_bhp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "reservasi" ADD CONSTRAINT "FK_fcda02184a2a199580e4c5a0774" FOREIGN KEY ("poliBagianId") REFERENCES "poli_bagian"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "reservasi" ADD CONSTRAINT "FK_14fa2860224a19d7cd9740d3a61" FOREIGN KEY ("dokterId") REFERENCES "dokter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "kunjungan" ADD CONSTRAINT "FK_815a30c04caaea6cac8e0bfd703" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "kunjungan" ADD CONSTRAINT "FK_97aacbe549c64c25bb53ba09014" FOREIGN KEY ("penyakitId") REFERENCES "penyakit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "obat" ADD CONSTRAINT "FK_674d2a594b62b922dba2a8b6fac" FOREIGN KEY ("kunjunganPoliId") REFERENCES "kunjungan_poli"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "obat" ADD CONSTRAINT "FK_2a6ec97144614ccc0bdcbb25b0d" FOREIGN KEY ("refObatId") REFERENCES "ref_obat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "tindakan" ADD CONSTRAINT "FK_a542af81b59d3e65d593a77b999" FOREIGN KEY ("refTindakanId") REFERENCES "ref_tindakan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "tindakan" ADD CONSTRAINT "FK_c47fb5ed4f33fcf2d0597c415b6" FOREIGN KEY ("kunjunganPoliId") REFERENCES "kunjungan_poli"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ADD CONSTRAINT "FK_0cefc763fa7bb353c3a9b8c533c" FOREIGN KEY ("poliBagianId") REFERENCES "poli_bagian"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ADD CONSTRAINT "FK_291f6490928c9a9a28876bb13bd" FOREIGN KEY ("dokterId") REFERENCES "dokter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ADD CONSTRAINT "FK_cc75ba6e19b43a6756e076808b7" FOREIGN KEY ("perawatId") REFERENCES "perawat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ADD CONSTRAINT "FK_3cd38b1b696f348d3117538254b" FOREIGN KEY ("penyakitId") REFERENCES "penyakit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE "kunjungan_poli" DROP CONSTRAINT "FK_3cd38b1b696f348d3117538254b"')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" DROP CONSTRAINT "FK_cc75ba6e19b43a6756e076808b7"')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" DROP CONSTRAINT "FK_291f6490928c9a9a28876bb13bd"')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" DROP CONSTRAINT "FK_0cefc763fa7bb353c3a9b8c533c"')
    await queryRunner.query('ALTER TABLE "tindakan" DROP CONSTRAINT "FK_c47fb5ed4f33fcf2d0597c415b6"')
    await queryRunner.query('ALTER TABLE "tindakan" DROP CONSTRAINT "FK_a542af81b59d3e65d593a77b999"')
    await queryRunner.query('ALTER TABLE "obat" DROP CONSTRAINT "FK_2a6ec97144614ccc0bdcbb25b0d"')
    await queryRunner.query('ALTER TABLE "obat" DROP CONSTRAINT "FK_674d2a594b62b922dba2a8b6fac"')
    await queryRunner.query('ALTER TABLE "kunjungan" DROP CONSTRAINT "FK_97aacbe549c64c25bb53ba09014"')
    await queryRunner.query('ALTER TABLE "kunjungan" DROP CONSTRAINT "FK_815a30c04caaea6cac8e0bfd703"')
    await queryRunner.query('ALTER TABLE "reservasi" DROP CONSTRAINT "FK_14fa2860224a19d7cd9740d3a61"')
    await queryRunner.query('ALTER TABLE "reservasi" DROP CONSTRAINT "FK_fcda02184a2a199580e4c5a0774"')
    await queryRunner.query('ALTER TABLE "bhp" DROP CONSTRAINT "FK_65192ba6227c61db00ddd026eb6"')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ALTER COLUMN "penyakitId" DROP NOT NULL')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ALTER COLUMN "perawatId" DROP NOT NULL')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ALTER COLUMN "dokterId" DROP NOT NULL')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ALTER COLUMN "poliBagianId" DROP NOT NULL')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ADD CONSTRAINT "FK_3cd38b1b696f348d3117538254b" FOREIGN KEY ("penyakitId") REFERENCES "penyakit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ADD CONSTRAINT "FK_cc75ba6e19b43a6756e076808b7" FOREIGN KEY ("perawatId") REFERENCES "perawat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ADD CONSTRAINT "FK_291f6490928c9a9a28876bb13bd" FOREIGN KEY ("dokterId") REFERENCES "dokter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "kunjungan_poli" ADD CONSTRAINT "FK_0cefc763fa7bb353c3a9b8c533c" FOREIGN KEY ("poliBagianId") REFERENCES "poli_bagian"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "tindakan" ALTER COLUMN "kunjunganPoliId" DROP NOT NULL')
    await queryRunner.query('ALTER TABLE "tindakan" ALTER COLUMN "refTindakanId" DROP NOT NULL')
    await queryRunner.query('ALTER TABLE "tindakan" ADD CONSTRAINT "FK_c47fb5ed4f33fcf2d0597c415b6" FOREIGN KEY ("kunjunganPoliId") REFERENCES "kunjungan_poli"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "tindakan" ADD CONSTRAINT "FK_a542af81b59d3e65d593a77b999" FOREIGN KEY ("refTindakanId") REFERENCES "ref_tindakan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "obat" ALTER COLUMN "refObatId" DROP NOT NULL')
    await queryRunner.query('ALTER TABLE "obat" ALTER COLUMN "kunjunganPoliId" DROP NOT NULL')
    await queryRunner.query('ALTER TABLE "obat" ADD CONSTRAINT "FK_2a6ec97144614ccc0bdcbb25b0d" FOREIGN KEY ("refObatId") REFERENCES "ref_obat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "obat" ADD CONSTRAINT "FK_674d2a594b62b922dba2a8b6fac" FOREIGN KEY ("kunjunganPoliId") REFERENCES "kunjungan_poli"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "kunjungan" ALTER COLUMN "penyakitId" DROP NOT NULL')
    await queryRunner.query('ALTER TABLE "kunjungan" ALTER COLUMN "userId" DROP NOT NULL')
    await queryRunner.query('ALTER TABLE "kunjungan" ADD CONSTRAINT "FK_97aacbe549c64c25bb53ba09014" FOREIGN KEY ("penyakitId") REFERENCES "penyakit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "kunjungan" ADD CONSTRAINT "FK_815a30c04caaea6cac8e0bfd703" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "reservasi" ALTER COLUMN "dokterId" DROP NOT NULL')
    await queryRunner.query('ALTER TABLE "reservasi" ALTER COLUMN "poliBagianId" DROP NOT NULL')
    await queryRunner.query('ALTER TABLE "reservasi" ADD CONSTRAINT "FK_14fa2860224a19d7cd9740d3a61" FOREIGN KEY ("dokterId") REFERENCES "dokter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "reservasi" ADD CONSTRAINT "FK_fcda02184a2a199580e4c5a0774" FOREIGN KEY ("poliBagianId") REFERENCES "poli_bagian"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "bhp" ALTER COLUMN "refBhpId" DROP NOT NULL')
    await queryRunner.query('ALTER TABLE "bhp" ADD CONSTRAINT "FK_65192ba6227c61db00ddd026eb6" FOREIGN KEY ("refBhpId") REFERENCES "ref_bhp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION')
    await queryRunner.query('ALTER TABLE "kunjungan" DROP COLUMN "reservasiId"')
    await queryRunner.query('ALTER TABLE "user" DROP COLUMN "poliBagianId"')
  }

}
