export const isProduction = process.env.NODE_ENV === 'production'
export const isStaging = process.env.NODE_ENV === 'staging'
export const COOKIE_NAME = 'sid'
export const FORGOT_PASSWORD_PREFIX = 'forgot-password:'
export const SELECTION_TEST_PREFIX = 'selection-test:'