# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches:
    - main

jobs:
  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Set production NODE_ENV
      if: github.base_ref == 'main'
      run: echo "NODE_ENV=production" >> $GITHUB_ENV
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build project
      run: yarn build
      
  build-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Set production NODE_ENV
      if: github.base_ref == 'main'
      run: echo "NODE_ENV=production" >> $GITHUB_ENV
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build project
      run: yarn build
